/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#11A8CD",
        "primary-hover": "#0e94b4",
        "primary-light": "#e8f7fa",
        "primary-container": "#0c4f60",
        "on-primary": "#ffffff",
        secondary: "#11A8CD",
        "secondary-fixed": "#11A8CD",
        "secondary-fixed-dim": "#0e94b4",
        "secondary-container": "#d3f2f8",
        tertiary: "#11A8CD",
        "on-tertiary": "#ffffff",
        surface: "#f8fbfd",
        "on-surface": "#0c2732",
        "on-background": "#0c2732",
        "surface-container-low": "#edf8fb",
        "surface-container-highest": "#d6f0f7",
        "surface-container": "#e4f5fa",
        "surface-container-high": "#ddf2f8",
        "surface-variant": "#d6f0f7",
        outline: "#5d8b96",
        "outline-variant": "#d0e7ed",
        "on-surface-variant": "#355964",
        "inverse-surface": "#122a33",
        "inverse-on-surface": "#eaf7fa",
        "on-primary-fixed": "#0c2732",
        "primary-fixed": "#d3f2f8",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-md": "24px",
        base: "8px",
        "stack-sm": "12px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "price-display": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "price-display": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
